<?php

namespace App\Services;

use App\Models\RefundRequest;
use App\Models\RefundWallet;
use App\Models\bookings;
use App\Models\orders;
use App\Models\payments;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class RefundService
{
    /**
     * Tạo yêu cầu hoàn tiền khi khách hủy tour
     */
    public function createRefundRequest($bookingId, $userId)
    {
        return DB::transaction(function () use ($bookingId, $userId) {
            $booking = bookings::findOrFail($bookingId);
            $order = orders::findOrFail($booking->order_id);

            // Kiểm tra quyền chủ sở hữu
            if ($order->user_id !== $userId) {
                throw new \Exception('Bạn không có quyền với đơn này');
            }

            // Kiểm tra trạng thái booking
            if ($booking->status === 'cancelled') {
                throw new \Exception('Đơn này đã bị hủy trước đó');
            }

            // Tính tiền cần hoàn lại
            $totalPaid = payments::where('order_id', $order->id)
                ->where('status', 'success')
                ->sum('amount');

            if ($totalPaid <= 0) {
                throw new \Exception('Không có tiền cần hoàn lại (chưa thanh toán hoặc đã hoàn trước)');
            }

            // Tạo RefundRequest
            $refundRequest = RefundRequest::create([
                'refund_code' => null, // Auto-generated by model boot
                'booking_id' => $bookingId,
                'order_id' => $order->id,
                'user_id' => $userId,
                'refund_amount' => $totalPaid,
                'status' => 'pending',
                'refund_method' => 'vnpay', // Mặc định hoàn tiền qua VNPay
            ]);

            // Cập nhật booking status thành 'pending_refund' để chưa hủy ngay
            $booking->status = 'pending_refund';
            $booking->save();

            return $refundRequest;
        });
    }

    /**
     * Admin duyệt yêu cầu hoàn tiền
     */
    public function approveRefundRequest($refundRequestId, $adminId, $note = null)
    {
        return DB::transaction(function () use ($refundRequestId, $adminId, $note) {
            $refundRequest = RefundRequest::findOrFail($refundRequestId);

            if (!$refundRequest->canApprove()) {
                throw new \Exception('Yêu cầu hoàn tiền này không thể được duyệt (trạng thái: ' . $refundRequest->status . ')');
            }

            $refundRequest->update([
                'status' => 'approved',
                'approved_by' => $adminId,
                'approved_at' => now(),
                'approval_note' => $note,
            ]);

            return $refundRequest;
        });
    }

    /**
     * Admin từ chối yêu cầu hoàn tiền
     */
    public function rejectRefundRequest($refundRequestId, $reason)
    {
        return DB::transaction(function () use ($refundRequestId, $reason) {
            $refundRequest = RefundRequest::findOrFail($refundRequestId);

            if (!$refundRequest->canReject()) {
                throw new \Exception('Yêu cầu hoàn tiền này không thể bị từ chối');
            }

            $refundRequest->update([
                'status' => 'rejected',
                'rejection_reason' => $reason,
                'rejected_at' => now(),
            ]);

            // Cập nhật lại booking status thành cancelled (hủy luôn)
            $booking = $refundRequest->booking;
            if ($booking->status === 'pending_refund') {
                $booking->status = 'cancelled';
                $booking->save();

                // Cập nhật order status
                $refundRequest->order->update(['status' => 'cancelled']);

                // Hoàn lại capacity
                if ($booking->departure) {
                    $slots = $booking->passengers->count();
                    if ($slots > 0) {
                        $newBooked = max(0, (int)$booking->departure->capacity_booked - $slots);
                        $booking->departure->update(['capacity_booked' => $newBooked]);
                    }
                }
            }

            return $refundRequest;
        });
    }

    /**
     * Xử lý hoàn tiền thành công (sau khi VNPay transfer thành công)
     */
    public function processRefundSuccess($refundRequestId, $vnpayData = [])
    {
        return DB::transaction(function () use ($refundRequestId, $vnpayData) {
            $refundRequest = RefundRequest::findOrFail($refundRequestId);

            if ($refundRequest->status !== 'approved') {
                throw new \Exception('Yêu cầu hoàn tiền không ở trạng thái được duyệt');
            }

            // Cập nhật thông tin VNPay nếu có
            if (!empty($vnpayData)) {
                $refundRequest->update([
                    'vnpay_payment_code' => $vnpayData['vnp_TxnRef'] ?? null,
                    'vnpay_transaction_no' => $vnpayData['vnp_TransactionNo'] ?? null,
                    'vnpay_bank_tran_no' => $vnpayData['vnp_BankTranNo'] ?? null,
                    'vnpay_response' => $vnpayData,
                ]);
            }

            // Cập nhật status thành refunded
            $refundRequest->update([
                'status' => 'refunded',
                'refunded_at' => now(),
            ]);

            // Cộng tiền vào ví của khách
            $user = $refundRequest->user;
            $wallet = $user->getOrCreateRefundWallet();
            
            $wallet->addBalance(
                $refundRequest->refund_amount,
                'refund',
                'Hoàn tiền từ hủy đơn ' . $refundRequest->refund_code,
                $refundRequest->id,
                'refund_request'
            );

            // Cập nhật booking status thành cancelled
            $booking = $refundRequest->booking;
            $booking->update(['status' => 'cancelled']);

            // Cập nhật order status
            $refundRequest->order->update(['status' => 'cancelled']);

            // Hoàn lại capacity
            if ($booking->departure) {
                $slots = $booking->passengers->count();
                if ($slots > 0) {
                    $newBooked = max(0, (int)$booking->departure->capacity_booked - $slots);
                    $booking->departure->update(['capacity_booked' => $newBooked]);
                }
            }

            return $refundRequest;
        });
    }

    /**
     * Xử lý hoàn tiền thất bại
     */
    public function processRefundFailed($refundRequestId, $errorMessage = null)
    {
        return DB::transaction(function () use ($refundRequestId, $errorMessage) {
            $refundRequest = RefundRequest::findOrFail($refundRequestId);

            $refundRequest->update([
                'status' => 'failed',
                'vnpay_response' => [
                    'error' => $errorMessage,
                    'failed_at' => now()->toIso8601String(),
                ],
            ]);

            return $refundRequest;
        });
    }

    /**
     * Lấy danh sách yêu cầu hoàn tiền chờ xử lý
     */
    public function getPendingRefundRequests($limit = 20)
    {
        return RefundRequest::pending()
            ->with(['booking.departure.tour', 'order', 'user'])
            ->latest()
            ->paginate($limit);
    }

    /**
     * Lấy thống kê hoàn tiền
     */
    public function getRefundStatistics()
    {
        $total = RefundRequest::sum('refund_amount');
        $pending = RefundRequest::pending()->sum('refund_amount');
        $approved = RefundRequest::approved()->sum('refund_amount');
        $refunded = RefundRequest::refunded()->sum('refund_amount');
        $rejected = RefundRequest::rejected()->sum('refund_amount');
        $failed = RefundRequest::failed()->sum('refund_amount');

        return [
            'total' => $total,
            'pending' => $pending,
            'approved' => $approved,
            'refunded' => $refunded,
            'rejected' => $rejected,
            'failed' => $failed,
            'pending_count' => RefundRequest::pending()->count(),
            'refunded_count' => RefundRequest::refunded()->count(),
        ];
    }

    /**
     * Lấy danh sách giao dịch ví của người dùng
     */
    public function getUserWalletTransactions($userId, $limit = 20)
    {
        $wallet = RefundWallet::where('user_id', $userId)->first();
        
        if (!$wallet) {
            return collect([]);
        }

        return $wallet->transactions()->paginate($limit);
    }

    /**
     * Rút tiền từ ví (tạo yêu cầu rút tiền)
     * (Tính năng nâng cao - có thể implement sau)
     */
    public function createWithdrawalRequest($userId, $amount, $bankInfo = [])
    {
        $user = User::findOrFail($userId);
        $wallet = $user->getOrCreateRefundWallet();

        if ($wallet->balance < $amount) {
            throw new \Exception('Số dư không đủ để rút tiền');
        }

        // Tạo withdrawal request (có thể tạo bảng riêng nếu cần)
        // Tạm thời chỉ trừ tiền khỏi ví
        $wallet->deductBalance(
            $amount,
            'withdrawal',
            'Rút tiền từ ví',
            null,
            'manual_withdrawal'
        );

        return [
            'success' => true,
            'message' => 'Yêu cầu rút tiền đã được tạo',
            'withdrawal_amount' => $amount,
            'remaining_balance' => $wallet->balance,
        ];
    }
}
